### PR TITLE
NEVER merge, just comparison: IHCC Zooma customizations

### PR DESCRIPTION
**Pull request by matentzn**

### CODE REVIEW

**Comment by matentzn** [comment]
Did you close this for a reason? There are some changes that I wanted to take care of later this year, esp ZOOMA2BackingUpDriver.java ones (I don't remember what was the issue but there was a problem here with read/edit rights).

**Comment by udp** [comment]
Sorry, thought this was an old PR you'd forgotten about. Did you know you can compare across forks without opening a PR though?

**Comment by matentzn** [comment]
Yes, I usually open a PR as a form of todolist -> I know that at some point, I will have to deal with it.. Dont worry about it, I have no moved the closed PR on my todolist - same thing for me :) Just wondering wether there are deeper reasons (like massive code changes) that I should know about

**Comment by udp** [comment]
That's no problem, feel free to make a new PR if you like. No massive code changes planned other than the new UI, which is already merged.

FYI the main branch of this repo is now master rather than stable, to bring it in line with the OLS and OXO repos.

**Comment by matentzn** [comment]
Thx!

**Pull request closed without merging**
